### ISSUE TITLE
BADA fuel flow dependent on timestep

### ISSUE THREAD

**Issue by remonvandenbrandt** [TUDelft-CNS-ATM/bluesky#176]
When using the BADA performance model, I get different results for the fuelflow when changing the timestep. This is probability caused by the hard-coded dt in the perfbada.py file

**Comment by jooste** [comment]
Hi Remon,

I see what you mean. the bada performance code updates at its own rate, which works fine as long as the simulation update rate is higher than the performance update rate, and is an integer multiple of it.

Currently the bada performance update rate is set to 10 Hz, so if you set your simdt to any value larger than 0.1 you will get issues. Ideally I would solve this with not every bit of bluesky managing its own update interval anymore with a `if self.t + self.dt <= bs.sim.simt`, but instead having a central piece of code that schedules this.

**Comment by rjdverbeek** [comment]
Hi Joost,

When I use the fuel model (BADA) I noticed that the weight is not always updated during each performance model timestep (perfbada.py). It looks like the performance model is sometimes skipping a beat, because it uses floats to keep track of a regular timestep.

I am proposing the following code to compensate for this behavior (perfbada.py):
line 337
`        if abs(simt - self.t0) >= self.dt:`
`            dt_current = abs(simt - self.t0)  # take the actual stepsize`
`            self.t0 = simt`
`        else:`
`            return`

line 553:
`        # self.mass = self.mass - self.ff*self.dt # Use fuelflow in kg/min`
`        self.mass = self.mass - self.ff * dt_current  # Use fuelflow in kg/min  #  use the actual stepsize`

**Comment by jooste** [comment]
Hi René,

Thanks for the suggestion. I've implemented it in commit fc0af67.

**Comment by MTMesfum** [comment]
Hi Joost,

Is this problem supposed to be solved?
There is probably another bug which is related to the timestep of perfbada.
I did implement these changes into BlueSky, but the problem still persists.
I'll create a new separate issue relating to this matter.

**Comment by jooste** [comment]
New timer which should fix this centrally is implemented in 8c7f7ae.
