### ISSUE TITLE
[BUG] ```setup.py``` requires numpy for fresh install

### ISSUE THREAD

**Issue by amorfinv** [TUDelft-CNS-ATM/bluesky#434]
I am installing BlueSky in fresh environment via

```pip install "bluesky-simulator[full]"```

and I get the following error

```
Collecting bluesky-simulator[full]
  Using cached bluesky-simulator-2022.9.19.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/fq/43m5ppyn55s1hxnxq_p5p6fh0000gn/T/pip-install-8os4dcbn/bluesky-simulator_80c53e5aecfc454aaf1e55485b4b1472/setup.py", line 7, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

I think it is because ```setup.py``` tries to import ```numpy```. However, because it is a fresh environment ```numpy``` is not yet installed. Works ok after I ```pip install numpy```.

**Comment by jooste** [comment]
Fixed in ee0be1b. Should become visible in next package release. You can try it yourself by building a source package (`python3 setup.py sdist`), and installing it in a fresh environment.

**Comment by pos-ki** [comment]
I believe I am still experiencing this problem in the `2024.7.1` version. The installation fails both with `uv`, and when installing it manually into a fresh virtual environment. I have tested this in `python` `3.10.15`, `3.11.10` and `3.12.7`.

```
Collecting bluesky-simulator[headless]
  Downloading bluesky_simulator-2024.7.1.tar.gz (347 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 347.7/347.7 kB 3.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8j58m4qb/bluesky-simulator_fc163fdf2df04ad89e5b33e44fa16277/setup.py", line 80, in <module>
          include_dirs=[get_numpy_include()],
        File "/tmp/pip-install-8j58m4qb/bluesky-simulator_fc163fdf2df04ad89e5b33e44fa16277/setup.py", line 9, in get_numpy_include
          import numpy
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```
